(() => {
    //If you want to add more images, add the link name and URL image URL in the array list below.
        const images_list = [
    {
        "url": "./source/box/g.jpg",
        "alt": "",
        "name": "image 1",
        "link": ""
    },
    {
        "url": "./source/box/q.jpg",
        "alt": "",
        "name": "image 2",
        "link": ""
    },
    {
        "url": "./source/box/g.jpg",
        "alt": "",
        "name": "image 3",
        "link": ""
    }
    
        ];
    
    // generated by https://www.html-code-generator.com/html/image-slideshow-generator
        let slider_id = document.querySelector("#hcg-slider-1");
    
        // append all images
        let dots_div = "";
        let images_div = "";
        for (let i = 0; i < images_list.length; i++) {
            // if no link without href="" tag
            let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
            images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                            '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
                            '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
                            '<span class="hcg-slide-text">'+images_list[i].name+'</span>'+
                         '</a>';
            dots_div += '<a href="#" class="hcg-slide-dot'+(i === 0 ? ' dot-active':'')+'" data-id="'+i+'">'+
            '<img src="'+images_list[i].url+'">'+'</a>';
        }
        slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
        slider_id.querySelector(".hcg-slide-dot-control").innerHTML = dots_div;
    
        let slide_index = 0;
    
        const images = slider_id.querySelectorAll(".hcg-slides");
        const dots = slider_id.querySelectorAll(".hcg-slide-dot");
        const showSlides = () => {
            if (slide_index > images.length-1) {
                slide_index = 0;
            }
            if (slide_index < 0) {
                slide_index = images.length-1;
            }
            for (let i = 0; i < images.length; i++) {
                images[i].style.display = "none";
                dots[i].classList.remove("dot-active");
                
                if (i == slide_index) {
                    images[i].style.display = "flex";
                    dots[i].classList.add("dot-active");
                }
            }
        }
    
        // const dot_click = event => {
        //     event.preventDefault();
        //     slide_index = event.target.dataset.id;
        //     showSlides();
        // }
    
        // for (let i = 0; i < dots.length; i++) {
        //     dots[i].addEventListener("click", dot_click, false);
        // }
        // auto play
        setInterval(() => {
            slide_index++;
            showSlides();
        }, 1000);
    
    })();



(() => {
        //If you want to add more images, add the link name and URL image URL in the array list below.
            const images_lista = [
                {
                    "url": "./source/box/g.jpg",
                    "alt": "",
                    "name": "image 1",
                    "link": ""
                },
                {
                    "url": "./source/box/q.jpg",
                    "alt": "",
                    "name": "image 2",
                    "link": ""
                },
                {
                    "url": "./source/box/g.jpg",
                    "alt": "",
                    "name": "image 3",
                    "link": ""
                }
               
               
            ];
        
        // generated by https://www.html-code-generator.com/html/image-slideshow-generator
            let slider_ida = document.querySelector("#hcg-slider-1a");
        
            // append all images
            let dots_diva = "";
            let images_diva = "";
            for (let i = 0; i < images_lista.length; i++) {
                // if no link without href="" tag
                let hrefa = (images_lista[i].link == "" ? "":' href="'+images_lista[i].link+'"');
                images_diva += '<a'+hrefa+' class="hcg-slidesa animateda"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                                '<span class="hcg-slide-numbera">'+(i+1)+'/'+images_lista.length+'</span>'+
                                '<img src="'+images_lista[i].url+'" alt="'+images_lista[i].name+'">'+
                                 '<span class="hcg-slide-texta">'+images_lista[i].name+'</span>'+
                             '</a>';
                dots_diva += '<a href="#" class="hcg-slide-dota'+(i === 0 ? ' dot-activea':'')+'" data-id="'+i+'">'+
                '<img src="'+images_lista[i].url+'" alt="'+images_lista[i].name+'">'+'</a>';
            }
            slider_ida.querySelector(".hcg-slider-bodya").innerHTML = images_diva;
            slider_ida.querySelector(".hcg-slide-dot-controla").innerHTML = dots_diva;
        
            let slide_indexa = 0;
        
            const imagesa = slider_ida.querySelectorAll(".hcg-slidesa");
            const dotsa = slider_ida.querySelectorAll(".hcg-slide-dota");
            const showSlidesa = () => {
                if (slide_indexa > imagesa.length-1) {
                    slide_indexa = 0;
                }
                if (slide_indexa < 0) {
                    slide_indexa = imagesa.length-1;
                }
                for (let i = 0; i < imagesa.length; i++) {
                    imagesa[i].style.display = "none";
                    dotsa[i].classList.remove("dot-activea");
                    if (i == slide_indexa) {
                        imagesa[i].style.display = "flex";
                        dotsa[i].classList.add("dot-activea");
                    }
                }
            }
        
            // const dot_clicka = event => {
            //     event.preventDefault();
            //     slide_indexa = event.target.dataset.id;
            //     showSlidesa();
            // }
        
            // for (let i = 0; i < dotsa.length; i++) {
            //     dotsa[i].addEventListener("click", dot_clicka, false);
            // }
            // auto play
            setInterval(() => {
                slide_indexa++;
                showSlidesa();
            }, 1444);
        
        })();



(() => {
            //If you want to add more images, add the link name and URL image URL in the array list below.
                const images_listaa = [
                    {
                        "url": "./source/box/g.jpg",
                        "alt": "",
                        "name": "image 1",
                        "link": ""
                    },
                    {
                        "url": "./source/box/q.jpg",
                        "alt": "",
                        "name": "image 2",
                        "link": ""
                    },
                    {
                        "url": "./source/box/g.jpg",
                        "alt": "",
                        "name": "image 3",
                        "link": ""
                    }
                   
                ];
            
            // generated by https://www.html-code-generator.com/html/image-slideshow-generator
                let slider_idaa = document.querySelector("#hcg-slider-1aa");
            
                // append all images
                let dots_divaa = "";
                let images_divaa = "";
                for (let i = 0; i < images_listaa.length; i++) {
                    // if no link without href="" tag
                    let hrefaa = (images_listaa[i].link == "" ? "":' href="'+images_listaa[i].link+'"');
                    images_divaa += '<a'+hrefaa+' class="hcg-slidesaa animatedaa"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                                    '<span class="hcg-slide-numberaa">'+(i+1)+'/'+images_listaa.length+'</span>'+
                                    '<img src="'+images_listaa[i].url+'" alt="'+images_listaa[i].name+'">'+
                                     '<span class="hcg-slide-textaa">'+images_listaa[i].name+'</span>'+
                                 '</a>';
                    dots_divaa += '<a href="#" class="hcg-slide-dotaa'+(i === 0 ? ' dot-activeaa':'')+'" data-id="'+i+'">'+
                    '<img src="'+images_listaa[i].url+'" alt="'+images_listaa[i].name+'">'+'</a>';
                }
                slider_idaa.querySelector(".hcg-slider-bodyaa").innerHTML = images_divaa;
                slider_idaa.querySelector(".hcg-slide-dot-controlaa").innerHTML = dots_divaa;
            
                let slide_indexaa = 0;
            
                const imagesaa = slider_idaa.querySelectorAll(".hcg-slidesaa");
                const dotsaa = slider_idaa.querySelectorAll(".hcg-slide-dotaa");
                const showSlidesaa = () => {
                    if (slide_indexaa > imagesaa.length-1) {
                        slide_indexaa = 0;
                    }
                    if (slide_indexaa < 0) {
                        slide_indexaa = imagesaa.length-1;
                    }
                    for (let i = 0; i < imagesaa.length; i++) {
                        imagesaa[i].style.display = "none";
                        dotsaa[i].classList.remove("dot-activeaa");
                        if (i == slide_indexaa) {
                            imagesaa[i].style.display = "flex";
                            dotsaa[i].classList.add("dot-activeaa");
                        }
                    }
                }
            
                // const dot_clickaa = event => {
                //     event.preventDefault();
                //     slide_indexaa = event.target.dataset.id;
                //     showSlidesaa();
                // }
            
                // for (let i = 0; i < dotsaa.length; i++) {
                //     dotsaa[i].addEventListener("click", dot_clickaa, false);
                // }
                // auto play
                setInterval(() => {
                    slide_indexaa++;
                    showSlidesaa();
                }, 1222);
            
            })();   
        
            
 (() => {
                //If you want to add more images, add the link name and URL image URL in the array list below.
                    const images_listq = [
                        {
                            "url": "./source/box/g.jpg",
                            "alt": "",
                            "name": "image 1",
                            "link": ""
                        },
                        {
                            "url": "./source/box/q.jpg",
                            "alt": "",
                            "name": "image 2",
                            "link": ""
                        },
                        {
                            "url": "./source/box/g.jpg",
                            "alt": "",
                            "name": "image 3",
                            "link": ""
                        }
                        
                    ];
                
                // generated by https://www.html-code-generator.com/html/image-slideshow-generator
                    let slider_idq = document.querySelector("#hcg-slider-1q");
                
                    // append all images
                    let dots_divq = "";
                    let images_divq = "";
                    for (let i = 0; i < images_listq.length; i++) {
                        // if no link without href="" tag
                        let hrefq = (images_listq[i].link == "" ? "":' href="'+images_listq[i].link+'"');
                        images_divq += '<a'+hrefq+' class="hcg-slidesq animatedq"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                                        '<span class="hcg-slide-numberq">'+(i+1)+'/'+images_listq.length+'</span>'+
                                        '<img src="'+images_listq[i].url+'" alt="'+images_listq[i].name+'">'+
                                        '<span class="hcg-slide-textq">'+images_listq[i].name+'</span>'+
                                     '</a>';
                        dots_divq += '<a href="#" class="hcg-slide-dotq'+(i === 0 ? ' dot-activeq':'')+'" data-id="'+i+'">'+
                        '<img src="'+images_listq[i].url+'" alt="'+images_listq[i].name+'">'+'</a>';
                    }
                    slider_idq.querySelector(".hcg-slider-bodyq").innerHTML = images_divq;
                    slider_idq.querySelector(".hcg-slide-dot-controlq").innerHTML = dots_divq;
                
                    let slide_indexq = 0;
                
                    const imagesq = slider_idq.querySelectorAll(".hcg-slidesq");
                    const dotsq = slider_idq.querySelectorAll(".hcg-slide-dotq");
                    const showSlidesq = () => {
                        if (slide_indexq > imagesq.length-1) {
                            slide_indexq = 0;
                        }
                        if (slide_indexq < 0) {
                            slide_indexq = imagesq.length-1;
                        }
                        for (let i = 0; i < imagesq.length; i++) {
                            imagesq[i].style.display = "none";
                            dotsq[i].classList.remove("dot-activeq");
                            if (i == slide_indexq) {
                                imagesq[i].style.display = "flex";
                                dotsq[i].classList.add("dot-activeq");
                            }
                        }
                    }
                
                    // const dot_clickq = event => {
                    //     event.preventDefault();
                    //     slide_indexq = event.target.dataset.id;
                    //     showSlidesq();
                    // }
                
                    // for (let i = 0; i < dotsq.length; i++) {
                    //     dotsq[i].addEventListener("click", dot_clickq, false);
                    // }
                    // auto play
                    setInterval(() => {
                        slide_indexq++;
                        showSlidesq();
                    }, 1333);
                
                })();           
            

    
                (() => {
                    //If you want to add more images, add the link name and URL image URL in the array list below.
                        const images_listqq = [
                            {
                                "url": "./source/box/g.jpg",
                                "alt": "",
                                "name": "image 1",
                                "link": ""
                            },
                            {
                                "url": "./source/box/q.jpg",
                                "alt": "",
                                "name": "image 2",
                                "link": ""
                            },
                            {
                                "url": "./source/box/g.jpg",
                                "alt": "",
                                "name": "image 3",
                                "link": ""
                            }
                           
                        ];
                    
                    // generated by https://www.html-code-generator.com/html/image-slideshow-generator
                        let slider_idqq = document.querySelector("#hcg-slider-1qq");
                    
                        // append all images
                        let dots_divqq = "";
                        let images_divqq = "";
                        for (let i = 0; i < images_listqq.length; i++) {
                            // if no link without href="" tag
                            let hrefqq= (images_listqq[i].link == "" ? "":' href="'+images_listqq[i].link+'"');
                            images_divqq += '<a'+hrefqq+' class="hcg-slidesqq animatedqq"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                                            '<span class="hcg-slide-numberqq">'+(i+1)+'/'+images_listqq.length+'</span>'+
                                            '<img src="'+images_listqq[i].url+'" alt="'+images_listqq[i].name+'">'+
                                            '<span class="hcg-slide-textqq">'+images_listqq[i].name+'</span>'+
                                         '</a>';
                            dots_divqq += '<a href="#" class="hcg-slide-dotqq'+(i === 0 ? ' dot-activeqq':'')+'" data-id="'+i+'">'+'<img src="'+images_listqq[i].url+'" alt="'+images_listqq[i].name+'">'+'</a>';
                        
                        }
                        slider_idqq.querySelector(".hcg-slider-bodyqq").innerHTML = images_divqq;
                        slider_idqq.querySelector(".hcg-slide-dot-controlqq").innerHTML = dots_divqq;
                    
                        let slide_indexqq = 0;
                    
                        const imagesqq = slider_idqq.querySelectorAll(".hcg-slidesqq");
                        const dotsqq = slider_idqq.querySelectorAll(".hcg-slide-dotqq");
                        const showSlidesqq = () => {
                            if (slide_indexqq > imagesqq.length-1) {
                                slide_indexqq = 0;
                            }
                            if (slide_indexqq < 0) {
                                slide_indexqq = imagesqq.length-1;
                            }
                            for (let i = 0; i < imagesqq.length; i++) {
                                imagesqq[i].style.display = "none";
                                dotsqq[i].classList.remove("dot-activeqq");
                                if (i == slide_indexqq) {
                                    imagesqq[i].style.display = "flex";
                                    dotsqq[i].classList.add("dot-activeqq");
                                }
                            }
                        }
                    
                        // const dot_clickqq = event => {
                        //     event.preventDefault();
                        //     slide_indexqq = event.target.dataset.id;
                        //     showSlidesqq();
                        // }
                    
                        // for (let i = 0; i < dotsqq.length; i++) {
                        //     dotsqq[i].addEventListener("click", dot_clickqq, false);
                        // }
                        // auto play
                        setInterval(() => {
                            slide_indexqq++;
                            showSlidesqq();
                        }, 1333);
                    
                    })();     